# Generated by Django 5.2.7 on 2025-11-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('score', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Puntuación')),
                ('episodes', models.IntegerField(default=0, verbose_name='Episodios')),
                ('type', models.CharField(choices=[('TV', 'TV'), ('Movie', 'Película'), ('OVA', 'OVA'), ('Other', 'Otro')], default='TV', max_length=20, verbose_name='Tipo')),
                ('image_url', models.URLField(max_length=500, verbose_name='URL de la Imagen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Anime',
                'verbose_name_plural': 'Animes',
                'ordering': ['-created_at'],
            },
        ),
    ]
