# Generated by Django 5.2.7 on 2025-11-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteAnime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mal_id', models.IntegerField(unique=True, verbose_name='ID de MyAnimeList')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('image_url', models.URLField(max_length=500, verbose_name='URL de la Imagen')),
                ('score', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Puntuación')),
                ('episodes', models.IntegerField(default=0, verbose_name='Episodios')),
                ('type', models.CharField(default='TV', max_length=20, verbose_name='Tipo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Anime Favorito (API)',
                'verbose_name_plural': 'Animes Favoritos (API)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='anime',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='Favorito'),
        ),
    ]
